spring:
  shardingsphere:
    mode:
      type: Memory
    datasource:
      names: ds1,ds2
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/nfrtest?useUnicode=true&useSSL=false&characterEncoding=utf-8
        username: root
        password: 123456
      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/platform?useUnicode=true&useSSL=false&characterEncoding=utf-8
        username: root
        password: 123456
    rules:
      sharding:
        tables:
          merchants:
            actual-data-nodes: ds2.merchants
          user:
            actual-data-nodes: ds1.user

    props:
      sql-show: true
logging:
  level:
    com.example.mybatis_plus.sys.mapper: debug
